---
ansible_ssh_port: 22
ansible_ssh_user: 'root'
ansible_ssh_pass: 'root'

timezone: 'Asia/Shanghai'

ca:
  # Certificate validity
  days: 100000
  kubernetes:
    location: /etc/kubernetes/pki
  etcd:
    location: /etc/kubernetes/pki/etcd

kubernetes:
  # defaullt: kubernetes
  name: kubernetes

  # cloud support
  cloud: 
    # choose: local or azure
    #   local: local data center (default)
    #   azure: azure cloud
    type: local
    file: /etc/kubernetes/cloud.conf

  ha:
    # virtual IP
    vip: 172.16.15.10
    mask: 16
    # interface: ens192

  # choose: none flannel calico canal
  #   none: not deployment any network plugin
  #   flannel: will deployment flannel plugin (default)
  #   calico: will deployment calico plugin
  #   canal: will deployment canal plugin
  network: canal
  settings:
    PodCIDR: 10.200.0.0/16
    SvcCIDR: 10.24.0.0/12
    SvcIP: 10.24.0.1
    DNSIP: 10.24.0.2
    NodePortRange: 30000-32767
    ClusterDomain: cluster.local

  # etcd parameter configuration
  etcd: 
    enablepprof: true
    autocompactionretention: 1
    debug: true
    datadir: /var/lib/etcd
    initialclustertoken: 'kubernetes'
    initialclusterstate: 'new'
  
  # docker parameter configuration
  docker:
    datadir: /var/lib/docker
    # Convert the json format to yaml
    daemon: 
      exec-opts:
        - "native.cgroupdriver=systemd"
      registry-mirrors:
        - "https://i3jtbyvy.mirror.aliyuncs.com"
      storage-driver: "overlay2"
      storage-opts: 
        - "overlay2.override_kernel_check=true"
      log-driver: "json-file"
      log-opts: 
        max-size: "500m"
        max-file: "2"
      debug: true

  # kubelet parameter configuration
  kubelet: 
    log:
      logLevel: 2
      logDir: /var/log/kubernetes
      logFile: kubelet.log
    pod_infra_container_image: gcr.io/google_containers/pause-amd64:3.1
    image_pull_progress_deadline: 2m

  # kube-apiserver parameter configuration
  apiserver: 
    bind: 0.0.0.0
    log:
      logLevel: 2
      logDir: /var/log/kubernetes
      logFile: kube-apiserver.log

  # kube-scheduler parameter configuration
  scheduler: 
    bind: 0.0.0.0
    log:
      logLevel: 2
      logDir: /var/log/kubernetes
      logFile: kube-scheduler.log

  # kube-controller-manager parameter configuration
  controllerManager:
    bind: 0.0.0.0
    PodCidr: 10.244.0.0/16
    SvcCidr: 10.96.0.0/12
    terminatedPodGcThreshold: 12500
    nodeStatusUpdate: Medium
    log:
      logLevel: 2
      logDir: /var/log/kubernetes
      logFile: kube-controller-manager.log

  # kube-proxy parameter configuration
  proxy:
    log:
      logLevel: 2
      logDir: /var/log/kubernetes
      logFile: kube-proxy.log

  addon:
    location: /etc/kubernetes/addon
    image: 
      coredns: coredns/coredns:1.6.7
      flannel: quay.io/coreos/flannel:v0.12.0
      canal:
        node: quay.io/calico/node:v3.1.7
        flannel: quay.io/coreos/flannel:v0.9.1
        cni: quay.io/calico/cni:v3.1.7
      calico: 
        node: quay.io/calico/node:v3.1.7
        cni: quay.io/calico/cni:v3.1.7
        typha: quay.io/calico/typha:v3.1.7