init:
	@[ -f ./all.yml ] || cp ./template/all.template all.yml
	@[ -f ./kubernetes.yml ] || cp ./template/kubernetes.template kubernetes.yml
	@echo "group vars is create, please modify according to requirements."