- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install elrepo
  yum:
    name: https://www.elrepo.org/elrepo-release-{{ ansible_distribution_major_version }}.el{{ ansible_distribution_major_version }}.elrepo.noarch.rpm
    state: present

- name: Install kernel-lt
  yum:
    name:
      - kernel-lt
      - kernel-lt-headers
      - kernel-lt-devel
    enablerepo: elrepo-kernel

- name: Grub2 set default
  shell: grub2-set-default 0

- name: Grub2 mkconfig
  shell: grub2-mkconfig -o /etc/grub2.cfg
