---
# tasks file for haproxy
- block:
    - name: Install applications
      package: 
        name: '{{ item }}'
        state: present
      with_items:
        - haproxy

    - name: Create applications configure files
      template: 
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - { src: 'haproxy.cfg.j2', dest: '/etc/haproxy/haproxy.cfg'}

    - name: Start the service
      systemd:
        name: haproxy
        enabled: yes
        state: restarted

    - name: Wait for haproxy
      wait_for:
        port: 8443
        delay: 15
        state: started
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      connection: local
  when: kubernetes.cloud.type == "local"