---
# tasks file for kube-proxy
- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - kube-proxy

- name: Create log directory
  file: 
    name: '{{ kubernetes.proxy.log.logDir }}'
    state: directory
    mode: '0755'

- name: Create data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ca.kubernetes.location }}'

- name: Create kube-proxy sa crb --- part.1
  copy: 
    src: '{{ item }}'
    dest: '/etc/kubernetes/{{ item }}'
  run_once: true
  with_items:
    - kube-proxy-crb.yml
    - kube-proxy-sa.yml
  when: "'kube-master' in group_names"

- name: Create kube-proxy sa crb --- part.2
  command: 'kubectl apply -f /etc/kubernetes/{{ item }}'
  run_once: true
  with_items:
    - kube-proxy-crb.yml
    - kube-proxy-sa.yml
  when: "'kube-master' in group_names"

- name: Register jwt token
  shell: |
    secret=$(kubectl -n kube-system get sa kube-proxy --output=jsonpath='{.secrets[0].name}')
    kubectl -n kube-system get secret/${secret} --output=jsonpath='{.data.token}'
  register: JWT_TOKEN

- name: Create kubeconfig
  shell: |
    kubectl config set-cluster {{ kubernetes.name | default("kubernetes") }} \
      --certificate-authority={{ ca.kubernetes.location }}/ca.crt \
      --server=https://{% if groups['kube-master'] | length !=1 %}{{ kubernetes.ha.vip }}:8443{% else %}{{ hostvars[groups['kube-master'][0]].inventory_hostname }}:6443{% endif %} \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}

    kubectl config set-context {{ kubernetes.name | default("kubernetes") }} \
      --cluster={{ kubernetes.name | default("kubernetes") }} \
      --user={{ kubernetes.name | default("kubernetes") }} \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}

    kubectl config set-credentials {{ kubernetes.name | default("kubernetes") }} \
      --token={{ JWT_TOKEN.stdout | b64encode }} \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}

    kubectl config use-context {{ kubernetes.name | default("kubernetes") }} --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}
  with_items:
    - { KUBE_CONFIG: 'kube-proxy.kubeconfig'}

- name: Install config file
  template: 
    src: kube-proxy.conf.j2
    dest: /etc/kubernetes/kube-proxy.conf

- name: Install systemd file
  template: 
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service

- name: Start the service
  systemd:
    name: kube-proxy
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Clean kube-proxy ca and crb yml file
  file:
    path: '/etc/kubernetes/{{ item }}'
    state: absent
  run_once: true
  with_items:
    - kube-proxy-crb.yml
    - kube-proxy-sa.yml
  when: "'kube-master' in group_names"