---
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY }}.yml"

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/bin/kube-proxy
    force: true
    mode: 0755
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: kube_proxy_pkg
  until: kube_proxy_pkg is succeeded
  retries: 5

- name: Create certificate directory
  file:
    name: /etc/kubernetes/pki
    state: directory

- name: Distribution certificate
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
        src: "/etc/ssl/kubernetes/ca.crt",
        dest: "/etc/kubernetes/pki/ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/ca.key",
        dest: "/etc/kubernetes/pki/ca.key",
        mode: 600,
      }

# - name: Check kube-proxy certificate expired(30 days)
#   community.crypto.openssl_certificate:
#     path: "/etc/kubernetes/pki/kube-proxy.crt"
#     provider: assertonly
#     valid_in: "2592000"
#   ignore_errors: yes
#   register: kube_proxy_certificate_expired

# - name: Create kube-proxy certificate
#   shell: |
#     openssl genrsa -out kube-proxy.key 2048 && \
#     openssl req -new -key kube-proxy.key -subj "/CN=system:kube-proxy/O=system:node-proxier" -out kube-proxy.csr && \
#     openssl x509 -req -in kube-proxy.csr -CA ca.crt -CAkey ca.key -CAcreateserial -extensions v3_req_client -extfile openssl.cnf -out kube-proxy.crt -days {{ kubernetes.ssl.days | default(3652) }}
#   args:
#     chdir: "/etc/kubernetes/pki"
#     executable: /bin/bash
#   register: kube_proxy_certificate
#   when: kube_proxy_certificate_expired.failed

- name: Generate kube-proxy private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-proxy.key
    size: 2048
    mode: 0600

- name: Generate kube-proxy csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kube-proxy.csr
    privatekey_path: /etc/kubernetes/pki/kube-proxy.key
    common_name: "system:kube-proxy"
    organization_name: "system:node-proxier"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth

- name: Generate kube-proxy certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-proxy.crt
    csr_path: /etc/kubernetes/pki/kube-proxy.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    mode: 0644

- name: Create kubeconfig
  shell: |
    {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ansible_default_ipv4.address, 6443 %}
    {% if inventory_hostname in groups['master'] %}
      {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ansible_default_ipv4.address, 6443 %}
    {% else %}
      {% if ha.type == "none" %}
        {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = hostvars[groups['master'][0]].inventory_hostname, 6443 %}
      {% else %}
        {% if ha.type == "slb" %}
          {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ha.vip, 8443 %}
        {% else %}
          {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ha.vip, 6443 %}
        {% endif %}
      {% endif %}
    {% endif %}

    /usr/local/bin/kubectl config set-cluster kubernetes \
      --embed-certs=true \
      --certificate-authority=/etc/kubernetes/pki/ca.crt \
      --server=https://{{ KUBE_APISERVER_ADDR }}:{{ KUBE_APISERVER_PORT }} \
      --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig

    /usr/local/bin/kubectl config set-credentials kube-proxy \
      --embed-certs=true \
      --client-certificate=/etc/kubernetes/pki/kube-proxy.crt \
      --client-key=/etc/kubernetes/pki/kube-proxy.key \
      --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig

    /usr/local/bin/kubectl config set-context kubernetes \
      --cluster=kubernetes \
      --user=kube-proxy \
      --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig

    /usr/local/bin/kubectl config use-context kubernetes --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig
  with_items:
    - {
        KUBE_USER: "kube-proxy",
        KUBE_CERT: "kube-proxy",
        KUBE_CONFIG: "kube-proxy.kubeconfig",
      }

- name: Change file permissions
  file:
    path: /etc/kubernetes/kube-proxy.kubeconfig
    mode: "0644"

- name: Install config file
  template:
    src: kube-proxy.yaml.j2
    dest: /etc/kubernetes/kube-proxy.yaml
  register: kube_proxy_conf

- name: Install systemd file
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  register: kube_proxy_systemd

- name: Start the service
  systemd:
    name: kube-proxy
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: kube_proxy_service
  when: kube_proxy_pkg.changed or kube_proxy_systemd.changed

- name: Health check
  uri:
    url: 'http://{% if proxy.bindAddress != "0.0.0.0" %}127.0.0.1{% else %}{{ ansible_default_ipv4.address }}{% endif %}:10256/healthz'
    validate_certs: no
  register: this
  until: 
    - "'ok' in this.content"
    - this.status == 200
  retries: 120
  delay: 1
  when: kube_proxy_service.changed
