---
# tasks file for cni
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY }}.yml"

- name: Create binary directory
  ansible.builtin.file:
    name: /opt/cni/bin
    state: directory
    mode: 0755

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: "/usr/local/src/cni-plugins-{{ ansible_system | lower }}-{% if ansible_architecture == 'aarch64' %}arm64{% elif ansible_architecture == 'x86_64' %}amd64{% endif %}-v{{ CNI_VERSION }}.tgz"
    mode: 0644
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME | default('') }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD | default('') }}"
    timeout: 3
  register: cni_pkg
  until: cni_pkg is succeeded
  retries: 10
  environment: "{{ proxy_env }}"

- name: Extract CNI
  ansible.builtin.unarchive:
    src: "/usr/local/src/cni-plugins-{{ ansible_system | lower }}-{% if ansible_architecture == 'aarch64' %}arm64{% elif ansible_architecture == 'x86_64' %}amd64{% endif %}-v{{ CNI_VERSION }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes
    owner: root
    group: root