---
# tasks file for cni
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY }}.yml"

- name: Create binary directory
  file:
    name: /opt/cni/bin
    state: directory
    mode: 0755

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: "/usr/local/src/cni-plugins-linux-amd64-v{{ CNI_VERSION }}.tgz"
    mode: 0644
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: cni_pkg
  until: cni_pkg is succeeded
  retries: 10

- name: Extract CNI
  unarchive:
    src: "/usr/local/src/cni-plugins-linux-amd64-v{{ CNI_VERSION }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes
    owner: root
    group: root