---
- name: Base environment configuration
  hosts: all
  become: true
  roles:
    - motd
    - common
    - chrony
    - kernel
  tags:
    - init

- name: Certificate of the cluster
  hosts: all
  become: true
  roles:
    - ca
  tags:
    - ca

- name: Deployment etcd cluster
  hosts: "{% if groups['etcd'] is not defined %}master{% else %}etcd{% endif %}"
  become: true
  vars:
    scale: false
  roles:
    - etcd
  tags:
    - etcd

- name: Initialization kubernetes dependence
  hosts: kubernetes
  become: true
  roles:
    - cni
    - ipvsadm

- name: Deployment kubernetes master
  hosts: master
  become: true
  roles:
    - haproxy
    - keepalived
    - "{% if RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
    - cleanup
  tags:
    - kube-master

- name: Deployment kubernetes worker
  hosts: worker
  become: true
  roles:
    - "{% if RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kubelet
    - kube-proxy
    - cleanup
  tags:
    - kube-worker

- name: Deployment kubernetes apps
  hosts: master
  roles:
    - apps
  tags:
    - apps