- name: Python3
  hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python2"
  tasks:
    - name: Install Python3
      ansible.builtin.package:
        name: python3
        state: latest

    - name: Upgrade pip
      pip:
        name: pip
        extra_args: "-U -i https://mirrors.aliyun.com/pypi/simple"
        executable: pip3