- name: Fix Python2 pip
  hosts: all
  tasks:
    - name: Install epel-release applications
      package:
        name: epel-release
        state: present

    - name: Generate an Kubernetes CA private key
      community.crypto.openssl_privatekey:
        path: /etc/ssl/kubernetes/ca.key
        size: 2048
      run_once: true

    - name: Generate an Kubernetes CA CSR
      community.crypto.openssl_csr:
        path: /etc/ssl/kubernetes/ca.csr
        privatekey_path: /etc/ssl/kubernetes/ca.key
        common_name: "kubernetes-ca"
      run_once: true

    - name: Sign Kubernetes CA CSR
      community.crypto.x509_certificate:
        path: /etc/ssl/kubernetes/ca.crt
        csr_path: /etc/ssl/kubernetes/ca.csr
        privatekey_path: /etc/ssl/kubernetes/ca.key
        provider: selfsigned
      run_once: true
