---
- name: Base environment configuration
  hosts: all
  vars:
    kernel_upgrade: True
  roles:
    - common
    - chrony
  tags:
    - common

- name: Certificate of the cluster
  hosts: localhost
  roles:
    - ca
  tags:
    - ca

- name: Deployment etcd cluster
  hosts: "{% if groups['kube-etcd'] is not defined %}kube-master{% else %}kube-etcd{% endif %}"
  roles:
    - etcd
  tags:
    - etcd

- name: Init all kubernetes node
  hosts: kubernetes
  roles:
    - docker
    - ipvs
    # - cni-plugins
  tags:
    - kubernetes-init

- name: Deployment kube master
  hosts: kube-master
  roles:
    - haproxy
    - keepalived
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
  tags:
    - kube-master

- name: Deployment kube minion
  hosts: kube-minion
  roles:
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-minion

- name: Deployment add-on
  hosts: kubernetes
  roles:
    - addons
  tags:
    - addons

- name: Deployment test
  hosts: kubernetes
  roles:
    - kube-proxy
  tags:
    - test