---
- name: Base environment configuration
  hosts: all
  become: yes
  roles:
    - common
    - chrony
    - kernel
    - cni
  tags:
    - common

- name: Certificate of the cluster
  hosts: all
  become: yes
  roles:
    - ca
  tags:
    - ca

- name: Deployment etcd cluster
  hosts: "{% if groups['etcd'] is not defined %}master{% else %}etcd{% endif %}"
  become: yes
  vars:
    scale: false
  roles:
    - etcd
  tags:
    - etcd

- name: Deployment kubernetes master
  hosts: master
  become: yes
  roles:
    - ipvsadm
    - haproxy
    - keepalived
    - "{% if RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
  tags:
    - kube-master

- name: Deployment kubernetes worker
  hosts: worker
  become: yes
  roles:
    - ipvsadm
    - "{% if RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker

- name: Clean up the data
  hosts: all
  become: yes
  roles:
    - cleanup
  tags:
    - cleanup

# - name: Deployment kubernetes add-on
#   hosts: master
#   become: yes
#   roles:
#     - addons/coredns
#     - addons/flannel
#     - addons/canal
#     - addons/calico
#     - addons/cilium
#     - addons/metrics
#   tags:
#     - addons

- name: Deployment kubernetes apps
  hosts: master
  roles:
    - apps
  tags:
    - apps