---
- name: Base environment configuration
  hosts: all
  vars:
    kernel_upgrade: True
  roles:
    - common
    - chrony
  tags:
    - common

- name: Certificate of the cluster
  hosts: localhost
  roles:
    - ca
  tags:
    - ca

- name: Deployment etcd cluster
  hosts: "{% if groups['etcd'] is not defined %}master{% else %}kube-etcd{% endif %}"
  roles:
    - etcd
  tags:
    - etcd

- name: Init all kubernetes node
  hosts: kubernetes
  roles:
    - docker
    - ipvs
    # - cni-plugins
  tags:
    - kubernetes-init

- name: Deployment kube master
  hosts: master
  roles:
    - haproxy
    - keepalived
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
  tags:
    - kube-master

- name: Deployment kube worker
  hosts: worker
  roles:
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker

- name: Deployment add-on
  hosts: kubernetes
  roles:
    - addons
  tags:
    - addons

# - name: Deployment test
#   hosts: kubernetes
#   roles:
#     - test
#   tags:
#     - test