---
- name: Base environment configuration
  hosts: worker
  become: yes
  roles:
    - prepare
    - motd
    - chrony
  tags:
    - common

- name: Certificate of the cluster
  hosts: all
  become: yes
  roles:
    - ca
  tags:
    - ca

- name: Deployment kubernetes worker
  hosts: worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - "{% if KUBE_RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kubelet
    - kube-proxy
    - cleanup
  tags:
    - kube-worker