---
- name: Base environment configuration
  hosts: worker
  become: yes
  roles:
    - common
    - chrony
    - kernel
  tags:
    - common

- name: Certificate of the cluster
  hosts: all
  become: yes
  roles:
    - ca
  tags:
    - ca

- name: Deployment kube worker
  hosts: worker
  become: yes
  roles:
    - cni
    - ipvsadm
    - "{% if RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker

- name: Clean up the data
  hosts: all
  become: yes
  roles:
    - cleanup
  tags:
    - cleanup