---
- name: Base environment configuration
  hosts: worker
  roles:
    - common
    - chrony
  tags:
    - common

- name: Init all kubernetes node
  hosts: worker
  roles:
    - ipvs
    # - cni-plugins
  tags:
    - kubernetes-init

- name: Deployment kube worker
  hosts: worker
  roles:
    - cni-plugins
    - docker
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker