---
- name: Base environment configuration
  hosts: worker
  roles:
    - common
    - chrony
  tags:
    - common

- name: Certificate of the cluster
  hosts: all
  roles:
    - ca
  tags:
    - ca

- name: Init all kubernetes node
  hosts: worker
  roles:
    - ipvs
  tags:
    - kubernetes-init

- name: Deployment kube worker
  hosts: worker
  roles:
    - cni-plugins
    - docker
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker

- name: Clean up the data
  hosts: all
  roles:
    - cleanup
  tags:
    - cleanup