- name: test kubeconfig module
  hosts: localhost
  tasks:
    - name: Check if a certificate is currently still valid, ignoring failures
      openssl_certificate:
        path: /root/csa.crt
        provider: assertonly
        valid_in: "1209600"
      ignore_errors: yes
      register: validity_check

    - name: debug
      debug: 
        msg: "{{ validity_check }}"

    # - name: Create a cluster on kubeconfig
    #   kubeconfig:
    #     path: /etc/kubernetes/test.kubeconfig
    #     type: cluster
    #     name: kubernetes
    #     server: https://127.0.0.1:6443
    #     ca: /etc/kubernetes/pki/ca.crt
    #   register: kubeconfig_cluster

    # - name: Create a user on kubeconfig
    #   kubeconfig:
    #     path: /etc/kubernetes/test.kubeconfig
    #     type: user
    #     name: admin
    #     certificate: /etc/kubernetes/pki/admin.crt
    #     certificate_key: /etc/kubernetes/pki/admin.key
    #   register: kubeconfig_user

    # - name: Create a context on kubeconfig
    #   kubeconfig:
    #     path: /etc/kubernetes/test.kubeconfig
    #     type: context
    #     name: "{{ kubeconfig_user.name }}@{{ kubeconfig_cluster.name }}"
    #     user: "{{ kubeconfig_user.name }}"
    #     cluster: "{{ kubeconfig_cluster.name }}"
    #     default: true