---
- name: Base environment configuration
  hosts: all
  roles:
    - common
    - chrony
  tags:
    - common

- name: Certificate of the cluster
  hosts: all
  become: yes
  roles:
    - ca
  tags:
    - ca

- name: Deployment etcd cluster
  serial: 1
  hosts: "{% if groups['etcd'] is not defined %}master{% else %}etcd{% endif %}"
  become: yes
  roles:
    - etcd
  tags:
    - etcd

- name: Initialization kubernetes dependence
  hosts: kubernetes
  become: yes
  roles:
    - cni
    - ipvsadm

- name: Deployment kube master
  serial: 1
  hosts: master
  roles:
    - "{% if RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
  tags:
    - kube-master

- name: Deployment kube worker
  serial: 1
  hosts: worker
  roles:
    - "{% if RUNTIME == 'docker' %}docker{% else %}containerd{% endif %}"
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker

- name: Clean up the data
  hosts: all
  roles:
    - cleanup
  tags:
    - cleanup