---
- name: Base environment configuration
  hosts: all
  roles:
    - common
    - chrony
  tags:
    - common

- name: Certificate of the cluster
  hosts: all
  become: yes
  roles:
    - ca
  tags:
    - ca

- name: Deployment etcd cluster
  hosts: "{% if groups['etcd'] is not defined %}master{% else %}kube-etcd{% endif %}"
  become: yes
  roles:
    - etcd
  tags:
    - etcd

- name: Init all kubernetes node
  hosts: kubernetes
  become: yes
  roles:
    - ipvsadm
  tags:
    - ipvsadm

- name: Deployment kube master
  hosts: master
  roles:
    - cni-plugins
    - docker
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
  tags:
    - kube-master

- name: Deployment kube worker
  hosts: worker
  roles:
    - cni-plugins
    - docker
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker

- name: Clean up the data
  hosts: all
  roles:
    - cleanup
  tags:
    - cleanup