---
# tasks file for done
- name: Master not scheduling
  shell: |
    {% if nodename is defined %}
      /usr/local/bin/kubectl taint node {{ nodename | lower}} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% else %}
      /usr/local/bin/kubectl taint node {{ hostvars[inventory_hostname].ansible_fqdn | lower }} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% endif %}
  when: 
    - not kubernetes.settings.master_run_pod | default(false) | bool and inventory_hostname in groups['master']

- name: Update node roles
  shell: |
    {% if nodename is defined %}
      /usr/local/bin/kubectl label node {{ nodename | lower }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% else %}
      /usr/local/bin/kubectl label node {{ hostvars[inventory_hostname].ansible_fqdn | lower }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% endif %}

- name: Clean kubeconfig for kube-minion nodes
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - ~/.kube
    - /etc/kubernetes/admin.kubeconfig
    - '{{ kubernetes.ssl.location }}/ca.key'
    - '{{ kubernetes.ssl.location }}/ca.srl'
    - '{{ kubernetes.ssl.location }}/admin.crt'
    - '{{ kubernetes.ssl.location }}/admin.key'
    - '{{ kubernetes.ssl.location }}/admin.csr'
    - '{{ kubernetes.ssl.location }}/etcd'
  when: inventory_hostname in groups['worker']