---
# tasks file for done
- name: Master not scheduling
  shell: |
    {% if nodename is defined %}
      kubectl taint node {{ nodename }} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% else %}
      kubectl taint node {{ hostvars[inventory_hostname].hostname }} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% endif %}
  when: 
    - kubernetes.settings.master_run_pod | default(false) | bool and inventory_hostname in groups['master']

- name: Update node roles
  shell: |
    {% if nodename is defined %}
      kubectl label node {{ nodename }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% else %}
      kubectl label node {{ hostvars[inventory_hostname].hostname }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% endif %}

- name: Clean kubeconfig for kube-minion nodes
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - ~/.kube
    - /etc/kubernetes/admin.kubeconfig
    - '{{ca.kubernetes.location }}/admin.crt'
    - '{{ca.kubernetes.location }}/admin.key'
  when: inventory_hostname in groups['worker']