---
# tasks file for done
- name: Master not scheduling
  shell: |
    {% if nodename is defined %}
      /usr/local/bin/kubectl taint node {{ nodename | lower}} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% else %}
      /usr/local/bin/kubectl taint node {{ hostvars[inventory_hostname].ansible_hostname | lower }} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% endif %}
  when:
    - not kubernetes.settings.master_run_pod | default(false) | bool and inventory_hostname in groups['master']

- name: Update node roles
  shell: |
    {% if nodename is defined %}
      /usr/local/bin/kubectl label node {{ nodename | lower }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% else %}
      /usr/local/bin/kubectl label node {{ hostvars[inventory_hostname].ansible_hostname | lower }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% endif %}
    {% if inventory_hostname in groups['master'] %}
      {% if nodename is defined %}
        /usr/local/bin/kubectl label node {{ nodename | lower }} node-role.kubernetes.io/control-plane="" --overwrite
      {% else %}
        /usr/local/bin/kubectl label node {{ hostvars[inventory_hostname].ansible_hostname | lower }} node-role.kubernetes.io/control-plane="" --overwrite
      {% endif %}
    {% endif %}

# - name: Clean kubeconfig for kube-minion nodes
#   file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - "~/.kube"
#     - "/etc/kubernetes/admin.kubeconfig"
#     - "/etc/kubernetes/pki/ca.key"
#     - "/etc/kubernetes/pki/ca.srl"
#     - "/etc/kubernetes/pki/admin.crt"
#     - "/etc/kubernetes/pki/admin.key"
#     - "/etc/kubernetes/pki/admin.csr"
#     - "/etc/kubernetes/pki/etcd"
#   when: inventory_hostname in groups['worker']
