---
# defaults file for containerd
containerd:
  datadir: /var/lib/containerd
  # auto create containerd primary partition
  # device: /dev/sdb
  daemon:
    sandbox_image: "registry.aliyuncs.com/google_containers/pause:3.5"
    endpoint:
      - "https://registry-1.docker.io"
      - "https://i3jtbyvy.mirror.aliyuncs.com"