download_url: '{{ NEXUS_DOMAIN_NAME }}/repository/{{ NEXUS_REPOSITORY }}/linux/static/stable/x86_64/docker-{{ KUBE_VERSION | component_version | community.general.json_query("runtime.docker") }}.tgz'
