---
# tasks file for apps
- name: Create application directory
  ansible.builtin.file:
    name: /etc/kubernetes/apps
    state: directory
    mode: "0755"

- name: Distribution cni to the cluster
  ansible.builtin.template:
    src: "{{ KUBE_NETWORK | default('calico')}}.yaml"
    dest: "/etc/kubernetes/apps/{{ KUBE_NETWORK | default('calico')}}.yaml"

- name: Apply cni to the cluster
  kubernetes.core.k8s:
    state: present
    src: "/etc/kubernetes/apps/{{ KUBE_NETWORK | default('calico')}}.yaml"
  run_once: true

- name: Distribution manifest to the cluster
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/kubernetes/apps/{{ item }}"
  with_items:
    - "metrics.yaml"
    - "coredns.yaml"

- name: Apply manifest to the cluster
  kubernetes.core.k8s:
    state: present
    src: "/etc/kubernetes/apps/{{ item }}"
    apply: true
    force: true
  run_once: true
  with_items:
    - "metrics.yaml"
    - "coredns.yaml"

# - name: Download manifest to the cluster
#   get_url:
#     url: "{{ item.url }}"
#     dest: '{{ apps.location | default("/etc/kubernetes/apps") }}/{{ item.name }}'
#   with_items: "{{ apps.files }}"
#   register: manifests
#   until: manifests is succeeded
#   retries: 10
#   environment: "{{ proxy_env | default({'http_proxy': '', 'https_proxy': '', 'no_proxy': ''}) }}"


