---
# tasks file for apps
- name: Create application directory
  ansible.builtin.file:
    name: /etc/kubernetes/apps
    state: directory
    mode: "0755"

- name: Distribution cni to the cluster
  ansible.builtin.template:
    src: "{{ KUBE_NETWORK | default('flannel')}}.yaml.j2"
    dest: "/etc/kubernetes/apps/{{ KUBE_NETWORK | default('flannel')}}.yaml"
  when:
    - KUBE_NETWORK != 'none'

- name: Apply cni to the cluster
  kubernetes.core.k8s:
    state: present
    src: "/etc/kubernetes/apps/{{ KUBE_NETWORK | default('flannel')}}.yaml"
  run_once: true
  when:
    - KUBE_NETWORK != 'none'

- name: Distribution manifest to the cluster
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/kubernetes/apps/{{ item.dest }}"
  with_items:
    - { "src": "metrics.yaml.j2", "dst": "metrics.yaml" }
    - { "src": "coredns.yaml.j2", "dst": "coredns.yaml" }

- name: Apply manifest to the cluster
  kubernetes.core.k8s:
    state: present
    src: "/etc/kubernetes/apps/{{ item }}"
  run_once: true
  with_items:
    - "metrics.yaml"
    - "coredns.yaml"
