---
# tasks file for ca
- name: Create certificate directory
  file: 
    name: '/etc/ssl/{{ kubernetes.project }}/etcd'
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Check kubernetes certificate expired(30 days)
  openssl_certificate:
    path: '/etc/ssl/{{ kubernetes.project }}/ca.crt'
    provider: assertonly
    valid_in: "2592000"
  ignore_errors: yes
  register: kubernetes_certificate_expired
  delegate_to: localhost
  run_once: true

# - name: Create kubernetes ca step 1
#   openssl_privatekey:
#     path: '/etc/ssl/{{ kubernetes.project }}/ca.key'
#     size: 2048

# - name: Create kubernetes ca step 2
#   openssl_csr:
#     path: '/etc/ssl/{{ kubernetes.project }}/ca.csr'
#     privatekey_path: '/etc/ssl/{{ kubernetes.project }}/ca.key'

# - name: Create kubernetes ca step 3
#   openssl_certificate:
#     provider: assertonly
#     path: '/etc/ssl/{{ kubernetes.project }}/ca.crt'
#     privatekey_path: '/etc/ssl/{{ kubernetes.project }}/ca.key'
#     csr_path: '/etc/ssl/{{ kubernetes.project }}/ca.csr'
#     subject:
#       CN: kubernetes-ca

- name: Create kubernetes ca
  shell: |
    openssl genrsa -out ca.key 2048 && \
    openssl req -x509 -new -nodes -key ca.key -subj "/CN=kubernetes-ca" -reqexts v3_req -extensions v3_ca -out ca.crt -days {{ kubernetes.ssl.days | default(3652) }}
    openssl req -new -key ca.key -out ca.csr -subj "/CN=kubernetes-ca"
  args:
    chdir: '/etc/ssl/{{ kubernetes.project }}'
    executable: /bin/bash
  delegate_to: localhost
  run_once: true
  when: kubernetes_certificate_expired.failed

- name: Check etcd certificate expired(30 days)
  openssl_certificate:
    path: '/etc/ssl/{{ kubernetes.project }}/etcd/ca.crt'
    provider: assertonly
    valid_in: "2592000"
  ignore_errors: yes
  register: etcd_certificate_expired
  delegate_to: localhost
  run_once: true

- name: Create etcd ca
  shell: |
    openssl genrsa -out etcd/ca.key 2048 && \
    openssl req -x509 -new -nodes -key etcd/ca.key -subj "/CN=etcd-ca" -reqexts v3_req -extensions v3_ca -out etcd/ca.crt -days {{ kubernetes.ssl.days | default(3652) }}
  args:
    chdir: '/etc/ssl/{{ kubernetes.project }}'
    executable: /bin/bash
  delegate_to: localhost
  run_once: true
  when: etcd_certificate_expired.failed

- name: Create certificate directory for kube nodes
  file: 
    name: '{{ kubernetes.ssl.location }}/etcd'
    state: directory
    mode: '0755'

- name: Create openssl template
  template: 
    src: 'openssl.cnf.j2'
    dest: '{{ kubernetes.ssl.location }}/openssl.cnf'
  register: openssl_conf