---
# tasks file for etcd
- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - etcd
    - etcdctl

- name: Create data directory
  file: 
    name: '{{ kubernetes.etcd.datadir }}'
    state: directory

- name: Create certificate directory
  file: 
    name: '{{ kubernetes.ssl.location }}/etcd'
    state: directory

- name: Distribution of certificate
  copy: 
    src: '{{ item }}'
    dest: '{{ kubernetes.ssl.location }}/etcd'
    owner: root
    group: root
  with_items:
    - '/etc/ssl/{{ kubernetes.project }}/etcd/ca.crt'
    - '/etc/ssl/{{ kubernetes.project }}/etcd/server.crt'
    - '/etc/ssl/{{ kubernetes.project }}/etcd/server.key'
    - '/etc/ssl/{{ kubernetes.project }}/etcd/peer.crt'
    - '/etc/ssl/{{ kubernetes.project }}/etcd/peer.key'

- name: Install systemd file
  template: 
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Start the service
  systemd:
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Wait for etcd
  wait_for:
    port: 2379
    delay: 15
    state: started
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
  connection: local

- name: Install health check command
  template: 
    src: etcd-health-check.j2
    dest: /usr/local/bin/etcd-health-check
    mode: 755

- name: Health check
  shell: |
    ETCDCTL_API=3
    /usr/local/bin/etcdctl --endpoints {{ ansible_default_ipv4.address }}:2379 --cacert {{ kubernetes.ssl.location }}/etcd/ca.crt --cert {{ kubernetes.ssl.location }}/etcd/server.crt --key {{ kubernetes.ssl.location }}/etcd/server.key endpoint health