---
# tasks file for kube-apiserver
- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - kube-apiserver

- name: Create log directory
  file: 
    name: '{{ kubernetes.apiserver.log.logDir }}'
    state: directory
    mode: '0755'

- name: Create data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ca.kubernetes.location }}'
    - '{{ca.kubernetes.location }}/etcd'

- name: Distribution of etcd certificate
  copy: 
    src: '{{ item }}'
    dest: '{{ca.kubernetes.location }}/etcd'
    owner: root
    group: root
  with_items:
    - '{{ca.kubernetes.location }}/etcd/ca.crt'

- name: Distribution of certificate
  copy: 
    src: '{{ item }}'
    dest: '{{ca.kubernetes.location }}'
    owner: root
    group: root
  with_items:
    - '{{ ca.kubernetes.location }}/ca.crt'
    - '{{ ca.kubernetes.location }}/apiserver-etcd-client.crt'
    - '{{ ca.kubernetes.location }}/apiserver-etcd-client.key'
    - '{{ ca.kubernetes.location }}/apiserver-kubelet-client.crt'
    - '{{ ca.kubernetes.location }}/apiserver-kubelet-client.key'
    - '{{ ca.kubernetes.location }}/sa.pub'
    - '{{ ca.kubernetes.location }}/sa.crt'
    - '{{ ca.kubernetes.location }}/apiserver.crt'
    - '{{ ca.kubernetes.location }}/apiserver.key'
    - '{{ ca.kubernetes.location }}/front-proxy-ca.crt'
    - '{{ ca.kubernetes.location }}/front-proxy-client.crt'
    - '{{ ca.kubernetes.location }}/front-proxy-client.key'
    - '{{ ca.kubernetes.location }}/admin.crt'
    - '{{ ca.kubernetes.location }}/admin.key'

- name: Stat encryption config file
  stat: 
    path: /etc/kubernetes/pki/encryption-config.yaml
  register: encryption_config_file

- name: Register encryption config
  shell: head -c 32 /dev/urandom | base64
  register: encryption_config
  run_once: true
  when: not encryption_config_file.stat.exists

- name: Install encryption config
  template: 
    src: encryption-config.yaml.j2
    dest: /etc/kubernetes/pki/encryption-config.yaml
  when: not encryption_config_file.stat.exists

- name: Install audit policy
  template: 
    src: audit-policy-minimal.yaml.j2
    dest: /etc/kubernetes/pki/audit-policy-minimal.yaml

- name: Install systemd file
  template: 
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service

- name: Start the service
  systemd:
    name: kube-apiserver
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Wait ApiServer
  wait_for:
    port: 6443
    delay: 30
    state: started

- name: Health check
  uri: 
    url: https://{{ ansible_default_ipv4.address }}:6443/healthz
    validate_certs: no
    return_content: yes
  register: this
  until: "'ok' in this.content"
  retries: 30
  delay: 5
  connection: local