---
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY }}.yml"

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/bin/kube-apiserver
    force: true
    mode: 0755
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: apiserver_pkg
  until: apiserver_pkg is succeeded
  retries: 10

- name: Create certificate directory
  file:
    name: /etc/kubernetes/pki
    state: directory

- name: Distribution certificate
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
        src: "/etc/ssl/kubernetes/etcd/ca.crt",
        dest: "/etc/kubernetes/pki/etcd/ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/etcd/ca.key",
        dest: "/etc/kubernetes/pki/etcd/ca.key",
        mode: 600,
      }
    - {
        src: "/etc/ssl/kubernetes/ca.crt",
        dest: "/etc/kubernetes/pki/ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/ca.key",
        dest: "/etc/kubernetes/pki/ca.key",
        mode: 600,
      }

# - name: Check kube-apiserver certificate expired(30 days)
#   community.crypto.openssl_certificate:
#     path: /etc/kubernetes/pki/apiserver.crt
#     provider: assertonly
#     valid_in: "2592000"
#   ignore_errors: yes
#   register: apiserver_certificate_expired

# - name: Create kube-apiserver certificate
#   shell: |
#     openssl genrsa -out apiserver.key 2048 && \
#     openssl req -new -key apiserver.key -subj "/CN=kube-apiserver/O=Kubernetes" -config openssl.cnf -out apiserver.csr && \
#     openssl x509 -req -in apiserver.csr -CA ca.crt -CAkey ca.key -CAcreateserial -extensions v3_req_apiserver -extfile openssl.cnf -out apiserver.crt -days {{ kubernetes.ssl.days | default(3652) }}
#   args:
#     chdir: "/etc/kubernetes/pki"
#     executable: /bin/bash
#   register: apiserver_certificate
#   when: apiserver_certificate_expired.failed or openssl_conf.changed
- name: Generate kube-apiserver private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/apiserver.key
    size: 2048
    mode: 0600

- name: Generate kube-apiserver csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/apiserver.csr
    privatekey_path: /etc/kubernetes/pki/apiserver.key
    common_name: "kube-apiserver"
    organization_name: "Kubernetes"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
      - clientAuth
    subject_alt_name: 
      - "DNS:localhost"
      - "DNS:kubernetes"
      - "DNS:kubernetes.default"
      - "DNS:kubernetes.default.svc"
      - "DNS:kubernetes.default.svc.{{ networking.dnsDomain | default(cluster.local) | split('.') | first }}"
      - "DNS:kubernetes.default.svc.{{ networking.dnsDomain | default(cluster.local) }}"
      - "IP:127.0.0.1"
      - "IP:{{ networking.SvcIP }}"
      - "IP:{{ ha.vip }}"
      - "IP:{{ ansible_default_ipv4.address }}"
  # with_dict:
  #   ips: "{% set IPS = [] %}{% if ha.vip is defined %}{{ IPS.append('IP:' + ha.vip) }}{{ IPS.append('IP:' + networking.SvcIP) }}{% endif %}{% if groups['etcd'] is not defined %}{% for host in groups['master'] %}{{ IPS.append('IP:' + host) }}{% endfor %}{% else %}{% for host in groups['etcd'] %}{{ IPS.append('IP:' + host)}}{% endfor %}{% endif %}{{ IPS.append('DNS:localhost')}}{{ IPS.append('DNS:kubernetes')}}{{ IPS.append('DNS:kubernetes.default')}}{{ IPS }}"

- name: Generate kube-apiserver certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/apiserver.crt
    csr_path: /etc/kubernetes/pki/apiserver.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    mode: 0644

# - name: Check front-proxy-client certificate expired(30 days)
#   community.crypto.openssl_certificate:
#     path: "/etc/kubernetes/pki/front-proxy-client.crt"
#     provider: assertonly
#     valid_in: "2592000"
#   ignore_errors: yes
#   register: front_proxy_client_certificate_expired

# - name: Create front-proxy-client certificate
#   shell: |
#     openssl genrsa -out front-proxy-client.key 2048 && \
#     openssl req -new -key front-proxy-client.key -subj "/CN=front-proxy-client" -out front-proxy-client.csr && \
#     openssl x509 -req -in front-proxy-client.csr -CA ca.crt -CAkey ca.key -CAcreateserial -extensions v3_req_client -extfile openssl.cnf -out front-proxy-client.crt -days {{ kubernetes.ssl.days | default(3652) }}
#   args:
#     chdir: "/etc/kubernetes/pki"
#     executable: /bin/bash
#   register: front_proxy_client_certificate
#   when: front_proxy_client_certificate_expired.failed or openssl_conf.changed

- name: Generate front-proxy-client private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/front-proxy-client.key
    size: 2048
    mode: 0600

- name: Generate front-proxy-client csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/front-proxy-client.csr
    privatekey_path: /etc/kubernetes/pki/front-proxy-client.key
    common_name: "front-proxy-client"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
      - clientAuth

- name: Generate front-proxy-client certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/front-proxy-client.crt
    csr_path: /etc/kubernetes/pki/front-proxy-client.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    mode: 0644

# - name: Check apiserver-kubelet-client certificate expired(30 days)
#   community.crypto.openssl_certificate:
#     path: "/etc/kubernetes/pki/apiserver-kubelet-client.crt"
#     provider: assertonly
#     valid_in: "2592000"
#   ignore_errors: yes
#   register: kubelet_client_certificate_expired
# - name: Create apiserver-kubelet-client certificate
#   shell: |
#     openssl genrsa -out apiserver-kubelet-client.key 2048 && \
#     openssl req -new -key apiserver-kubelet-client.key -subj "/CN=apiserver-kubelet-client/O=system:masters" -out apiserver-kubelet-client.csr && \
#     openssl x509 -req -in apiserver-kubelet-client.csr -CA ca.crt -CAkey ca.key -CAcreateserial -extensions v3_req_client -extfile openssl.cnf -out apiserver-kubelet-client.crt -days {{ kubernetes.ssl.days | default(3652) }}
#   args:
#     chdir: "/etc/kubernetes/pki"
#     executable: /bin/bash
#   register: kubelet_client_certificate
#   when: kubelet_client_certificate_expired.failed or openssl_conf.changed

- name: Generate apiserver-kubelet-client private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/apiserver-kubelet-client.key
    size: 2048
    mode: 0600

- name: Generate apiserver-kubelet-client csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/apiserver-kubelet-client.csr
    privatekey_path: /etc/kubernetes/pki/apiserver-kubelet-client.key
    common_name: "apiserver-kubelet-client"
    organization_name: "system:masters"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
      - clientAuth

- name: Generate apiserver-kubelet-client certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/apiserver-kubelet-client.crt
    csr_path: /etc/kubernetes/pki/apiserver-kubelet-client.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    mode: 0644

# - name: Check apiserver-etcd-client certificate expired(30 days)
#   community.crypto.openssl_certificate:
#     path: "/etc/kubernetes/pki/apiserver-etcd-client.crt"
#     provider: assertonly
#     valid_in: "2592000"
#   ignore_errors: yes
#   register: apiserver_etcd_client_certificate_expired
# - name: Create apiserver etcd client certificate
#   shell: |
#     openssl genrsa -out apiserver-etcd-client.key 2048 && \
#     openssl req -new -key apiserver-etcd-client.key -subj "/CN=apiserver-etcd-client/O=system:masters" -out apiserver-etcd-client.csr && \
#     openssl x509 -in apiserver-etcd-client.csr -req -CA etcd/ca.crt -CAkey etcd/ca.key -CAcreateserial -extensions v3_req_etcd -extfile openssl.cnf -out apiserver-etcd-client.crt -days {{ kubernetes.ssl.days | default(3652) }}
#   args:
#     chdir: "/etc/kubernetes/pki"
#     executable: /bin/bash
#   register: apiserver_etcd_client_certificate
#   when: apiserver_etcd_client_certificate_expired.failed or openssl_conf.changed
- name: Generate apiserver-etcd-client private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/apiserver-etcd-client.key
    size: 2048
    mode: 0600

- name: Generate apiserver-etcd-client csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/apiserver-etcd-client.csr
    privatekey_path: /etc/kubernetes/pki/apiserver-etcd-client.key
    common_name: "apiserver-etcd-client"
    organization_name: "system:masters"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
      - clientAuth

- name: Generate apiserver-etcd-client certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/apiserver-etcd-client.crt
    csr_path: /etc/kubernetes/pki/apiserver-etcd-client.csr
    ownca_path: /etc/kubernetes/pki/etcd/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/etcd/ca.key
    provider: ownca
    mode: 0644

- name: Install encryption config
  template:
    src: encryption-config.yaml.j2
    dest: /etc/kubernetes/encryption-config.yaml
    mode: "0644"

- name: Install audit policy
  template:
    src: audit-policy-minimal.yaml.j2
    dest: /etc/kubernetes/audit-policy-minimal.yaml
    mode: "0644"
  register: audit_policy

- name: Install admission control config
  template:
    src: admission-control-config.yaml.j2
    dest: /etc/kubernetes/admission-control-config.yaml
    mode: "0644"
  when:
    - apiServer.admissionControlConfigFile is defined
    - apiServer.admissionControlConfigFile | length >= 1

- name: Create admission control config plugins files
  ansible.builtin.file:
    path: "/etc/kubernetes/{{ item.path }}"
    state: touch
  with_items: "{{ apiServer.admissionControlConfigFile }}"
  when:
    - apiServer.admissionControlConfigFile is defined
    - apiServer.admissionControlConfigFile | length >= 1

- name: Install admission control config plugins
  blockinfile:
    path: "/etc/kubernetes/{{ item.path }}"
    block: |
      {{ item.configuration | to_nice_yaml(indent=2) }}
  with_items: "{{ apiServer.admissionControlConfigFile }}"
  when:
    - apiServer.admissionControlConfigFile is defined
    - apiServer.admissionControlConfigFile | length >= 1

- name: Configuration cloud provider
  template:
    src: cloud.conf.j2
    dest: /etc/kubernetes/cloud.conf
  when: cloudProvider is defined

- name: Install systemd file
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  register: apiserver_systemd

- name: Start the service
  systemd:
    name: kube-apiserver
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: apiserver_service
  when: apiserver_pkg.changed or audit_policy.changed or apiserver_systemd.changed

- name: Waiting for the service
  wait_for:
    port: 6443
    delay: 30
    state: started
  when: apiserver_service.changed

- name: Health check
  uri:
    url: 'https://{% if apiServer.bindAddress != "0.0.0.0" %}127.0.0.1{% else %}{{ ansible_default_ipv4.address }}{% endif %}:6443/healthz'
    client_cert: "/etc/kubernetes/pki/admin.crt"
    client_key: "/etc/kubernetes/pki/admin.key"
    validate_certs: no
    return_content: yes
  register: this
  until: "'ok' in this.content"
  retries: 30
  delay: 5
  when: apiserver_service.changed
