package:
  - conntrack
  - net-tools
  - sysstat
  - tar
  - unzip
  - tcpdump
  - telnet
  - lsof
  - strace
  - wget
  - psmisc
  - ipset
  - socat
  - bash-completion
  - nfs-common
  - dnsutils
  - python3-pip
  - python3-setuptools
  - jq
  - bcron