---
# tasks file for keepalived
- block:
    - name: Install applications
      package: 
        name: '{{ item }}'
        state: present
      with_items:
        - keepalived
      register: keepalived_pkg

    - name: Create applications configure files
      template: 
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - { src: 'keepalived.conf.j2', dest: '/etc/keepalived/keepalived.conf'}
        - { src: 'check_haproxy.sh.j2', dest: '/etc/keepalived/check_haproxy.sh'}
      register: keepalived_cfg

    - name: Start the service
      systemd:
        name: keepalived
        enabled: yes
        state: restarted
      when: keepalived_pkg.changed or keepalived_cfg.changed
  when: kubernetes.cloud.type == "local" and kubernetes.ha.vip is defined and groups['master'] | length > 1