---
# tasks file for keepalived
- name: Install applications
  package: 
    name: '{{ item }}'
    state: present
  with_items:
    - keepalived

- name: Create applications configure files
  template: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'keepalived.conf.j2', dest: '/etc/keepalived/keepalived.conf'}
    - { src: 'check_haproxy.sh.j2', dest: '/etc/keepalived/check_haproxy.sh'}

- name: Start the service
  systemd:
    name: keepalived
    enabled: yes
    state: restarted