---
# defaults file for kube-apiserver
apiServer:
  bindAddress: "0.0.0.0"
  encryption: Tsg7sO4Ki/W3s9bfwGfTi8ECcp+/3uDedQMq6rLQTIY= # head -c 32 /dev/urandom | base64
  certSANs:
    - "DNS:*.kubernetes.local"
  admissionControlConfigFile:
    - name: EventRateLimit
      path: EventRateLimit.yaml
      configuration:
        apiVersion: eventratelimit.admission.k8s.io/v1alpha1
        kind: Configuration
        limits:
          - type: Namespace
            qps: 50
            burst: 100
            cacheSize: 2000
  extraArgs:
    - "--event-ttl=4h"
    - "--anonymous-auth=false"
    - "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
    - "--service-node-port-range=30000-32767"
    - "--runtime-config=api/all=true"
    - "--authorization-mode=Node,RBAC"
    - "--profiling=false"
    - "--enable-admission-plugins=AlwaysPullImages,ServiceAccount,NamespaceLifecycle,NodeRestriction,LimitRanger,PersistentVolumeClaimResize,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority"
    - "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
    - "--feature-gates=TTLAfterFinished=true"
    - "--logging-format=json"
  log:
    level: 1
