---
# tasks file for apps
- block:
    - name: Create application directory
      file: 
        name: '{{ apps.location | default("/etc/kubernetes/apps") }}'
        state: directory
        mode: '0755'

    - name: Download manifests
      get_url: 
        url: '{{ item }}'
        dest: '{{ apps.location | default("/etc/kubernetes/apps") }}'
      with_items: '{{ apps.files }}'

    - name: Deployment application
      shell: '/usr/local/bin/kubectl apply -f {{ item }}'
      run_once: true
      with_items: '{{ apps.files }}'
  when: apps is defined