---
# tasks file for apps
- block:
    - name: Create application directory
      file:
        name: '{{ apps.location | default("/etc/kubernetes/apps") }}'
        state: directory
        mode: "0755"

    - name: Download manifests
      get_url:
        url: "{{ item.url }}"
        dest: '{{ apps.location | default("/etc/kubernetes/apps") }}/{{ item.name }}'
      with_items: "{{ apps.files }}"
      register: manifests
      until: manifests is succeeded
      retries: 10

    - name: Deployment application
      shell: "/usr/local/bin/kubectl apply -f {{ apps.location | default('/etc/kubernetes/apps') }}/{{ item.name }}"
      run_once: true
      with_items: "{{ apps.files }}"
  when: apps is defined