---
# tasks file for cni
- name: Create binary directory
  file: 
    name: /opt/cni/bin
    state: directory
    mode: '0755'
  when: (not master_run_pod | default(false) | bool and inventory_hostname in groups['master']) or (inventory_hostname in groups['worker'])

- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /opt/cni/bin/
    mode: 0755
  with_items:
    - bandwidth
    - bridge
    - dhcp
    - firewall
    - flannel
    - host-device
    - host-local
    - ipvlan
    - loopback
    - macvlan
    - portmap
    - ptp
    - sbr
    - static
    - tuning
    - vlan
  when: (not master_run_pod | default(false) | bool and inventory_hostname in groups['master']) or (inventory_hostname in groups['worker'])