---
# tasks file for cni
- name: Create binary directory
  file: 
    name: /opt/cni/bin
    state: directory
    mode: '0755'
  when: kubernetes.network == "flannel"  or kubernetes.network == "cilium"

- name: Set OS dependent variables
  include_vars: '{{ DOWNLOAD_WAY }}.yml'
  when: kubernetes.network == "flannel"  or kubernetes.network == "cilium"

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: "/usr/local/src/cni-plugins-linux-amd64-v{{ CNI_VERSION }}.tgz"
    mode: 0644
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: cni_pkg
  until: cni_pkg is succeeded
  retries: 10
  when: kubernetes.network == "flannel"  or kubernetes.network == "cilium"

- name: Extract CNI
  unarchive:
    src: "/usr/local/src/cni-plugins-linux-amd64-v{{ CNI_VERSION }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes
  when: kubernetes.network == "flannel"  or kubernetes.network == "cilium"