---
# defaults file for kube-scheduler
scheduler:
  extraArgs:
    - "--profiling=false"
    - "--port=0"
    - "--feature-gates=TTLAfterFinished=true"
    - "--logging-format=json"
  log:
    level: 1