- name: Install epel-release applications
  dnf: 
    name: epel-release
    state: present

- name: Install some applications
  dnf: 
    name: '{{ item }}'
    state: present
  with_items: "{{ package }}"