- name: Upgrade all packages, excluding kernel related packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: Install epel-release applications
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Install some applications
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package }}"
