---
# tasks file for calico
- block:
  - name: Create calico data directory
    file: 
      name: '{{ item }}'
      state: directory
      mode: '0755'
    with_items:
      - '{{ kubernetes.addon.location }}/calico'
    when: inventory_hostname in groups['master']

  - name: Stat calico yaml file
    stat: 
      path: '{{ kubernetes.addon.location }}/calico/calico.yaml'
    register: calico_yaml_file
    run_once: true

  - name: Clean old deployment
    shell: 'kubectl delete -f {{ kubernetes.addon.location }}/calico/calico.yaml'
    run_once: true
    when: calico_yaml_file.stat.exists

  - name: Waiting deployment delete
    shell: kubectl get po -n kube-system
    register: waiting_for_delete_deployment_done
    until: waiting_for_delete_deployment_done.rc == 0 and waiting_for_delete_deployment_done.stdout.find("calico") == -1
    retries: 15
    delay: 5
    changed_when: false
    when: calico_yaml_file.stat.exists
    run_once: true

  - name: Deployment calico --- part.1
    template: 
      src: '{{ item.src }}'
      dest: '{{ kubernetes.addon.location }}/{{ item.dest }}'
    with_items:
      - { src: 'calico/calico.yaml.j2', dest: 'calico/calico.yaml' }
    when: inventory_hostname in groups['master']

  - name: Deployment calico --- part.2
    shell: |
      kubectl apply -f {{ kubernetes.addon.location }}/{{ item }}
    with_items:
      - calico/calico.yaml
    run_once: true
    when: inventory_hostname in groups['master']
  when: kubernetes.network == "calico"