---
# Ansible settings
ansible_ssh_port: 22
ansible_ssh_user: "vagrant"
# ansible_ssh_pass: "root"
# ansible_sudo_user: "root"
# ansible_sudo_pass: "root"
ansible_become: "{% if ansible_ssh_user != 'root' %}yes{% else %}no{% endif %}"
ansible_python_interpreter: "/usr/bin/python3"

# Porxy Setting
proxy_env:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

# timezone settings, default is Asia/Shanghai
timezone: "Asia/Shanghai"

modprobe:
  filename: /etc/modules-load.d/00-k8s.conf
  params:
    - br_netfilter
    - nf_conntrack
    - overlay
    - xt_REDIRECT
    - xt_owner
    - ip_tables
    - ip6table_filter

ipvs:
  filename: /etc/modules-load.d/01-k8s.conf
  params:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh

sysctl:
  filename: /etc/sysctl.d/100-kubernetes.conf
  params:
    net.ipv6.ip_forward: 1
    net.ipv6.conf.all.forwarding: 1
    net.ipv6.conf.all.disable_ipv6: 0
    net.ipv6.conf.default.disable_ipv6: 0
    net.ipv6.conf.lo.disable_ipv6: 0
    net.ipv4.tcp_keepalive_time: 600
    net.ipv4.tcp_keepalive_intvl: 30
    net.ipv4.tcp_keepalive_probes: 10
    net.ipv4.neigh.default.gc_stale_time: 120
    net.ipv4.conf.all.rp_filter: 0
    net.ipv4.conf.default.rp_filter: 0
    net.ipv4.conf.default.arp_announce: 2
    net.ipv4.conf.lo.arp_announce: 2
    net.ipv4.conf.all.arp_announce: 2
    net.ipv4.ip_forward: 1
    net.ipv4.tcp_max_tw_buckets: 5000
    net.ipv4.tcp_syncookies: 1
    net.ipv4.tcp_max_syn_backlog: 1024
    net.ipv4.tcp_synack_retries: 2
    net.bridge.bridge-nf-call-ip6tables: 1
    net.bridge.bridge-nf-call-iptables: 1
    net.bridge.bridge-nf-call-arptables: 1
    net.netfilter.nf_conntrack_max: 10485760
    fs.inotify.max_user_watches: 524288
    fs.may_detach_mounts: 1
    fs.file-max: 52706963
    fs.nr_open: 52706963
    vm.swappiness: 0
    vm.overcommit_memory: 1
    vm.panic_on_oom: 0
    net.netfilter.nf_conntrack_tcp_timeout_established: 300
    net.netfilter.nf_conntrack_tcp_timeout_close_wait: 3600
    net.core.netdev_max_backlog: 10000
    kernel.pid_max: 65535
    net.ipv4.tcp_congestion_control: bbr
    net.ipv4.neigh.default.gc_thresh1: 1024
    net.ipv4.neigh.default.gc_thresh2: 4096
    net.ipv4.neigh.default.gc_thresh3: 8192
    net.netfilter.nf_conntrack_buckets: 655360
    fs.inotify.max_user_instances: 524288
    net.core.default_qdisc: fq
    net.core.rmem_max: 2500000
    vm.max_map_count: 262144

limits:
  - { domain: "*", limit_type: "soft", limit_item: "nproc", value: 65536 }
  - { domain: "*", limit_type: "hard", limit_item: "nproc", value: 65536 }
  - { domain: "*", limit_type: "soft", limit_item: "nofile", value: 65536 }
  - { domain: "*", limit_type: "hard", limit_item: "nofile", value: 65536 }
  - { domain: "root", limit_type: "soft", limit_item: "nofile", value: 65536 }
  - { domain: "root", limit_type: "hard", limit_item: "nofile", value: 65536 }
  - { domain: "root", limit_type: "soft", limit_item: "nproc", value: "unlimited" }
  - { domain: "root", limit_type: "hard", limit_item: "nproc", value: "unlimited" }

# OS firewalld
firewall:
  enabled: false

kernel:
  enabled: false