# this file about the version args
1.13.*:
  etcd:
    extraArgs:
      - "--auto-compaction-retention=1"

  apiServer:
    extraArgs:
      - "--event-ttl=4h"
      - "--anonymous-auth=false"
      - "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
      - "--service-node-port-range=30000-32767"
      - "--runtime-config=api/all=true"
      - "--authorization-mode=Node,RBAC"
      - "--profiling=false"
      - "--enable-admission-plugins=AlwaysPullImages,ServiceAccount,NamespaceLifecycle,NodeRestriction,LimitRanger,PersistentVolumeClaimResize,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority"
      - "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
      - "--feature-gates=TTLAfterFinished=true"
      - "--port=0"

  scheduler:
    bindAddress: "0.0.0.0"
    extraArgs:
      - "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
      - "--profiling=false"
      - "--feature-gates=TTLAfterFinished=true"