svc_name: firewalld

package:
  - conntrack
  - net-tools
  - sysstat
  - tar
  - unzip
  - tcpdump
  - telnet
  - lsof
  - strace
  - wget
  - psmisc
  - ipset
  - socat
  - bash-completion
  - nfs-utils
  - bind-utils
  - python3-pip
  - python2-pip
  - python-netaddr
  - python36-netaddr # need epel
  - python3-setuptools
  - jq