---
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY }}.yml"

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/bin/kube-controller-manager
    force: true
    mode: 0755
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: controllermanager_pkg
  until: controllermanager_pkg is succeeded
  retries: 10

- name: Create certificate directory
  file:
    name: /etc/kubernetes/pki
    state: directory

- name: Distribution certificate
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
        src: "/etc/ssl/kubernetes/ca.crt",
        dest: "/etc/kubernetes/pki/ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/ca.key",
        dest: "/etc/kubernetes/pki/ca.key",
        mode: 600,
      }
    - {
        src: "/etc/ssl/kubernetes/front-proxy-ca.crt",
        dest: "/etc/kubernetes/pki/front-proxy-ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/front-proxy-ca.key",
        dest: "/etc/kubernetes/pki/front-proxy-ca.key",
        mode: 600,
      }
    - {
        src: "/etc/ssl/kubernetes/sa.key",
        dest: "/etc/kubernetes/pki/sa.key",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/sa.pub",
        dest: "/etc/kubernetes/pki/sa.pub",
        mode: 600,
      }

- name: Generate kube-controller-manager private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-controller-manager.key
    size: 2048
    mode: 0600

- name: Generate kube-controller-manager csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kube-controller-manager.csr
    privatekey_path: /etc/kubernetes/pki/kube-controller-manager.key
    common_name: "system:kube-controller-manager"
    organization_name: "system:kube-controller-manager"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth

- name: Generate kube-controller-manager certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-controller-manager.crt
    csr_path: /etc/kubernetes/pki/kube-controller-manager.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    mode: 0644

- name: Create kubeconfig
  shell: |
    {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ansible_default_ipv4.address, 6443 %}
    {% if inventory_hostname in groups['master'] %}
      {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ansible_default_ipv4.address, 6443 %}
    {% else %}
      {% if ha.type == "none" %}
        {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = hostvars[groups['master'][0]].inventory_hostname, 6443 %}
      {% else %}
        {% if ha.type == "slb" %}
          {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ha.vip, 8443 %}
        {% else %}
          {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ha.vip, 6443 %}
        {% endif %}
      {% endif %}
    {% endif %}

    /usr/local/bin/kubectl config set-cluster kubernetes \
      --embed-certs=true \
      --certificate-authority=/etc/kubernetes/pki/ca.crt \
      --server=https://{{ KUBE_APISERVER_ADDR }}:{{ KUBE_APISERVER_PORT }} \
      --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig

    /usr/local/bin/kubectl config set-credentials system:kube-controller-manager \
      --embed-certs=true \
      --client-certificate=/etc/kubernetes/pki/{{ item.KUBE_CERT }}.crt \
      --client-key=/etc/kubernetes/pki/{{ item.KUBE_CERT }}.key \
      --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig

    /usr/local/bin/kubectl config set-context system:kube-controller-manager@kubernetes \
      --cluster=kubernetes \
      --user=system:kube-controller-manager \
      --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig

    /usr/local/bin/kubectl config use-context system:kube-controller-manager@kubernetes --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig
  with_items:
    - {
        KUBE_USER: "system:kube-controller-manager",
        KUBE_CERT: "kube-controller-manager",
        KUBE_CONFIG: "kube-controller-manager.kubeconfig",
      }

- name: Install systemd file
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  register: controllermanager_systemd

- name: Start the service
  systemd:
    name: kube-controller-manager
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: controllermanager_service
  when: controllermanager_pkg.changed or controllermanager_systemd.changed

- name: Waiting for the service
  wait_for:
    port: 10257
    delay: 30
    state: started
  when: controllermanager_service.changed

- name: Health check
  uri:
    url: 'https://127.0.0.1:10257/healthz'
    validate_certs: no
    return_content: yes
    client_cert: "/etc/kubernetes/pki/kube-controller-manager.crt"
    client_key: "/etc/kubernetes/pki/kube-controller-manager.key"
  register: this
  until: 
    - "'ok' in this.content"
    - this.status == 200
  retries: 120
  delay: 1
  when: controllermanager_service.changed