---
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY }}.yml"

- name: Download package
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/bin/kube-controller-manager
    force: true
    mode: 0755
    owner: root
    group: root
    url_username: "{{ NEXUS_USERNAME | default('') }}"
    url_password: "{{ NEXUS_PASSWORD | default('') }}"
    timeout: 3
  register: controller_pkg
  until: controller_pkg is succeeded
  retries: 15
  environment: "{{ proxy_env | default({'http_proxy': '', 'https_proxy': '', 'no_proxy': ''}) }}"

- name: Create certificate directory
  ansible.builtin.file:
    name: /etc/kubernetes/pki
    state: directory

- name: Distribution certificate by local
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
        src: "/etc/ssl/kubernetes/ca.crt",
        dest: "/etc/kubernetes/pki/ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/ca.key",
        dest: "/etc/kubernetes/pki/ca.key",
        mode: 600,
      }
    - {
        src: "/etc/ssl/kubernetes/front-proxy-ca.crt",
        dest: "/etc/kubernetes/pki/front-proxy-ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/front-proxy-ca.key",
        dest: "/etc/kubernetes/pki/front-proxy-ca.key",
        mode: 600,
      }
    - {
        src: "/etc/ssl/kubernetes/sa.key",
        dest: "/etc/kubernetes/pki/sa.key",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/sa.pub",
        dest: "/etc/kubernetes/pki/sa.pub",
        mode: 600,
      }
  when: not PKI_URL is defined

- name: Distribution certificate by pki server
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    checksum: "{{ item.checksum }}"
    owner: root
    group: root
    timeout: 3
  retries: 3
  with_items:
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/ca.crt",
        dest: "/etc/kubernetes/pki/ca.crt",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/ca.crt.sha256sum",
        mode: 644,
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/ca.key",
        dest: "/etc/kubernetes/pki/ca.key",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/ca.key.sha256sum",
        mode: 600,
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/front-proxy-ca.crt",
        dest: "/etc/kubernetes/pki/front-proxy-ca.crt",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/front-proxy-ca.crt.sha256sum",
        mode: 644,
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/front-proxy-ca.key",
        dest: "/etc/kubernetes/pki/front-proxy-ca.key",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/front-proxy-ca.key.sha256sum",
        mode: 600,
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/sa.key",
        dest: "/etc/kubernetes/pki/sa.key",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/sa.key.sha256sum",
        mode: 644,
      }
    - {
        url: "{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/sa.pub",
        dest: "/etc/kubernetes/pki/sa.pub",
        checksum: "sha256:{{ PKI_URL }}/{{ PROJECT_NAME }}/{{ PROJECT_ENV }}/sa.pub.sha256sum",
        mode: 600,
      }
  when: PKI_URL is defined

- name: Generate kube-controller-manager private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-controller-manager.key
    size: 2048
    mode: 0600
  register: controller_tls_key

- name: Generate kube-controller-manager csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kube-controller-manager.csr
    privatekey_path: /etc/kubernetes/pki/kube-controller-manager.key
    common_name: "system:kube-controller-manager"
    organization_name: "system:kube-controller-manager"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
  changed_when: True
  notify: Clean kube-controller-manager csr

- name: Generate kube-controller-manager certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-controller-manager.crt
    csr_path: /etc/kubernetes/pki/kube-controller-manager.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    mode: 0644
  register: controller_tls_crt

- name: Create kubeconfig
  ansible.builtin.template:
    src: kube-controller-manager.kubeconfig.j2
    dest: /etc/kubernetes/kube-controller-manager.kubeconfig
    mode: 0644
  register: controller_kubeconfig_cfg

- name: Install systemd file
  ansible.builtin.template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  register: controller_systemd_cfg

- name: Start the service
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: controller_systemd
  when: controller_pkg.changed or controller_tls_key.changed or controller_tls_crt.changed or controller_kubeconfig_cfg.changed or controller_systemd_cfg.changed

- name: Waiting for the service
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 10257
    delay: 30
    state: started
  when: controller_systemd.changed

- name: Health check
  uri:
    url: "https://{{ inventory_hostname | ip_format }}:10257/healthz"
    validate_certs: no
    return_content: yes
    client_cert: "/etc/kubernetes/pki/kube-controller-manager.crt"
    client_key: "/etc/kubernetes/pki/kube-controller-manager.key"
  register: this
  until: 
    - "'ok' in this.content"
    - this.status == 200
  retries: 120
  delay: 1
  when: controller_systemd.changed