---
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY }}.yml"

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/bin/kube-controller-manager
    force: true
    mode: 0755
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: controllermanager_pkg
  until: controllermanager_pkg is succeeded
  retries: 10

- name: Create certificate directory
  file:
    name: /etc/kubernetes/pki
    state: directory

- name: Distribution certificate
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
        src: "/etc/ssl/kubernetes/ca.crt",
        dest: "/etc/kubernetes/pki/ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/ca.key",
        dest: "/etc/kubernetes/pki/ca.key",
        mode: 600,
      }
    - {
        src: "/etc/ssl/kubernetes/front-proxy-ca.crt",
        dest: "/etc/kubernetes/pki/front-proxy-ca.crt",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/front-proxy-ca.key",
        dest: "/etc/kubernetes/pki/front-proxy-ca.key",
        mode: 600,
      }
    - {
        src: "/etc/ssl/kubernetes/sa.key",
        dest: "/etc/kubernetes/pki/sa.key",
        mode: 644,
      }
    - {
        src: "/etc/ssl/kubernetes/sa.pub",
        dest: "/etc/kubernetes/pki/sa.pub",
        mode: 600,
      }

- name: Generate kube-controller-manager private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-controller-manager.key
    size: 2048
    mode: 0600

- name: Generate kube-controller-manager csr
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kube-controller-manager.csr
    privatekey_path: /etc/kubernetes/pki/kube-controller-manager.key
    common_name: "system:kube-controller-manager"
    organization_name: "system:kube-controller-manager"
    basic_constraints_critical: yes
    basic_constraints:
      - "CA:FALSE"
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth

- name: Generate kube-controller-manager certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-controller-manager.crt
    csr_path: /etc/kubernetes/pki/kube-controller-manager.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    mode: 0644

- name: Create kubeconfig
  template:
    src: kube-controller-manager.kubeconfig.j2
    dest: /etc/kubernetes/kube-controller-manager.kubeconfig
    mode: 0600

- name: Install systemd file
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

- name: Start the service
  systemd:
    name: kube-controller-manager
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Waiting for the service
  wait_for:
    port: 10257
    delay: 30
    state: started

- name: Health check
  uri:
    url: 'https://127.0.0.1:10257/healthz'
    validate_certs: no
    return_content: yes
    client_cert: "/etc/kubernetes/pki/kube-controller-manager.crt"
    client_key: "/etc/kubernetes/pki/kube-controller-manager.key"
  register: this
  until: 
    - "'ok' in this.content"
    - this.status == 200
  retries: 120
  delay: 1