---
# tasks file for kube-controller-manager
- name: Try Install the binary of local file
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - kube-controller-manager
  register: controllermanager_pkg

- name: Download some applications
  include: "download.yml"

- name: Set OS dependent variables
  include_vars: '{{ DOWNLOAD_WAY }}.yml'
  when: controllermanager_pkg.failed

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/bin/kube-controller-manager
    mode: 0755
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
  register: controllermanager_bin
  until: controllermanager_bin is succeeded
  retries: 5
  when: controllermanager_pkg.failed

- name: Create log directory
  file: 
    name: '{{ kubernetes.controllerManager.log.logDir }}'
    state: directory
    mode: '0755'

- name: Configuration logrotate
  template: 
    src: kube-controller-manager.logrotate.j2
    dest: /etc/logrotate.d/kube-controller-manager

- name: Create ssl directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ kubernetes.ssl.location }}'

- name: Distribution certificate
  copy: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '{{ item.mode }}'
  with_items:
    - { src: '/etc/ssl/{{ kubernetes.project }}/ca.crt', dest: '{{ kubernetes.ssl.location }}/ca.crt', mode: 644 }
    - { src: '/etc/ssl/{{ kubernetes.project }}/ca.key', dest: '{{ kubernetes.ssl.location }}/ca.key', mode: 600 }

# - name: Check kube-controller-manager certificate expired(30 days)
#   shell: |
#     [ -f kube-controller-manager.crt ] && 
#     openssl x509 -in kube-controller-manager.crt -noout -text -checkend 2592000
#   register: kube_controller_manager_certificate_expired
#   ignore_errors: True
#   args:
#     chdir: '{{ kubernetes.ssl.location }}'
#     executable: /bin/bash
- name: Check kube-controller-manager certificate expired(30 days)
  openssl_certificate:
    path: '{{ kubernetes.ssl.location }}/kube-controller-manager.crt'
    provider: assertonly
    valid_in: "2592000"
  ignore_errors: yes
  register: kube_controller_manager_certificate_expired

- name: Create kube-controller-manager
  shell: |
    openssl genrsa -out kube-controller-manager.key 2048 && \
    openssl req -new -key kube-controller-manager.key -subj "/CN=system:kube-controller-manager/O=system:kube-controller-manager" -out kube-controller-manager.csr && \
    openssl x509 -req -in kube-controller-manager.csr -CA ca.crt -CAkey ca.key -CAcreateserial -extensions v3_req_client -extfile openssl.cnf -out kube-controller-manager.crt -days {{ kubernetes.ssl.days | default(3652) }}
  args:
    chdir: '{{ kubernetes.ssl.location }}'
    executable: /bin/bash
  register: kube_controller_manager_certificate
  when: kube_controller_manager_certificate_expired.failed

- name: Create kubeconfig
  shell: |
    {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ansible_default_ipv4.address, 6443 %}
    {% if inventory_hostname in groups['master'] %}
      {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = ansible_default_ipv4.address, 6443 %}
    {% else %}
      {% if kubernetes.ha.vip is defined %}
        {% if kubernetes.cloud.type == "local" %}
          {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = kubernetes.ha.vip, 8443 %}
        {% else %}
           {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = kubernetes.ha.vip, 6443 %}
        {% endif %}
      {% else %}
        {% set KUBE_APISERVER_ADDR, KUBE_APISERVER_PORT = hostvars[groups['master'][0]].inventory_hostname, 6443 %}
      {% endif %}
    {% endif %}

    /usr/local/bin/kubectl config set-cluster {{ kubernetes.name | default("kubernetes") }} \
      --embed-certs=true \
      --certificate-authority={{ kubernetes.ssl.location }}/ca.crt \
      --server=https://{{ KUBE_APISERVER_ADDR }}:{{ KUBE_APISERVER_PORT }} \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}

    /usr/local/bin/kubectl config set-credentials {{ item.KUBE_USER }} \
      --embed-certs=true \
      --client-certificate={{ kubernetes.ssl.location }}/{{ item.KUBE_CERT }}.crt \
      --client-key={{ kubernetes.ssl.location }}/{{ item.KUBE_CERT }}.key \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}

    /usr/local/bin/kubectl config set-context {{ item.KUBE_USER }}@{{ kubernetes.name | default("kubernetes") }} \
      --cluster={{ kubernetes.name | default("kubernetes") }} \
      --user={{ item.KUBE_USER }} \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}

    /usr/local/bin/kubectl config use-context {{ item.KUBE_USER }}@{{ kubernetes.name | default("kubernetes") }} --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }} 
  with_items:
    - { KUBE_USER: 'system:kube-controller-manager', KUBE_CERT: "kube-controller-manager", KUBE_CONFIG: 'kube-controller-manager.kubeconfig' }
  register: controllermanager_kubeconfig
  when: kube_controller_manager_certificate.changed

- name: Install systemd file
  template: 
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  register: controllermanager_systemd

- name: Start the service
  systemd:
    name: kube-controller-manager
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: controllermanager_service
  when: controllermanager_bin.changed or kube_controller_manager_certificate.changed or controllermanager_kubeconfig.changed or controllermanager_systemd.changed

- name: Waiting for the service
  wait_for:
    port: 10252
    delay: 30
    state: started
  when: controllermanager_service.changed

- name: Health check
  uri: 
    url: 'http://{% if kubernetes.controllerManager.bind != "0.0.0.0" %}127.0.0.1{% else %}{{ ansible_default_ipv4.address }}{% endif %}:10252/healthz'
    validate_certs: no
    return_content: yes
  register: this
  until: "'ok' in this.content"
  retries: 30
  delay: 5
  connection: local
  when: controllermanager_service.changed