name: Auto Release Pachage

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          tar -zcf /tmp/kube-ansible-online.tar.gz ../kube-ansible
          export GIT_TAG=${{ github.ref_name }}
          ./scripts/nexus.py download --quiet --kubernetes ${GIT_TAG:1}
          rm -rf ./scripts/__pycache__
          tar -zcf /tmp/kube-ansible-offline.tar.gz ../kube-ansible
          ls -lha

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset(kube-ansible-online)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/kube-ansible-online.tar.gz
          asset_name: kube-ansible-online.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset(kube-ansible-offline)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/kube-ansible-offline.tar.gz
          asset_name: kube-ansible-offline.tar.gz
          asset_content_type: application/gzip
