---
# tasks file for containerd
- name: Set OS dependent variables
  include_vars: "{{ DOWNLOAD_WAY | default('official') }}.yml"

- name: Download package
  get_url:
    url: "{{ download_url }}"
    dest: "/usr/local/src/containerd-{{ KUBE_VERSION | component_version | community.general.json_query('runtime.containerd') }}-{{ ansible_system | lower }}-{% if ansible_architecture == 'aarch64' %}arm64{% elif ansible_architecture == 'x86_64' %}amd64{% endif %}.tar.gz"
    mode: 0644
    owner: root
    group: root
    url_username: "{{ NEXUS_USERNAME | default('') }}"
    url_password: "{{ NEXUS_PASSWORD | default('') }}"
    timeout: 3
  register: containerd_pkg
  until: containerd_pkg is succeeded
  retries: 10
  notify: Start Containerd
  environment: "{{ proxy_env | default({'http_proxy': '', 'https_proxy': '', 'no_proxy': ''}) }}"

- name: Extract Containerd package
  ansible.builtin.unarchive:
    src: "/usr/local/src/containerd-{{ KUBE_VERSION | component_version | community.general.json_query('runtime.containerd') }}-{{ ansible_system | lower }}-{% if ansible_architecture == 'aarch64' %}arm64{% elif ansible_architecture == 'x86_64' %}amd64{% endif %}.tar.gz"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    extra_opts:
      - --strip-components=1 --exclude=opt --exclude=etc
  notify: Start Containerd

- name: Configuration Crictl
  ansible.builtin.template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml

- name: Create Configuration directory
  ansible.builtin.file:
    name: /etc/containerd
    state: directory
    mode: "0755"

- name: Create a containerd primary partition
  community.general.filesystem:
    fstype: xfs
    dev: "{{ containerd.device }}"
    state: present
  when: containerd.device is defined

- name: Mount containerd root dir
  ansible.posix.mount:
    src: "{{ containerd.device }}"
    path: /var/lib/containerd
    fstype: xfs
    opts: defaults,pquota
    state: mounted
  when: containerd.device is defined

- name: Configuration Containerd
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify: Start Containerd

- name: Install systemd file
  ansible.builtin.template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  notify: Start Containerd

- name: Install crictl completion
  ansible.builtin.copy:
    src: crictl.sh
    dest: /etc/bash_completion.d/crictl
    owner: root
    group: root
