---
# tasks file for containerd
- name: Download RunC
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc8/runc.amd64
    dest: /usr/local/bin/runc
    mode: '0755'
  notify: Start Containerd

- name: Download Containerd
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.3.0/containerd-1.3.0.linux-amd64.tar.gz
    dest: /usr/local/src/containerd-1.3.0.linux-amd64.tar.gz
    mode: '0755'
  notify: Start Containerd

- name: Extract Containerd
  unarchive:
    src: /usr/local/src/containerd-1.3.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
  notify: Start Containerd

- name: Download Crictl
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.16.1/crictl-v1.16.1-linux-amd64.tar.gz
    dest: /usr/local/src/crictl-v1.16.1-linux-amd64.tar.gz
    mode: '0755'
  notify: Start Containerd

- name: Configuration Crictl
  template: 
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
  
- name: Extract Crictl
  unarchive:
    src: /usr/local/src/crictl-v1.16.1-linux-amd64.tar.gz
    dest: /usr/local/bin

- name: Create Configuration directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /etc/containerd


- name: Configuration Containerd
  template: 
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify: Start Containerd

- name: Install systemd file
  template: 
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  notify: Start Containerd