---
# tasks file for containerd
- name: Download RunC
  get_url:
    url: '{{ runc_download_url }}'
    dest: /usr/local/bin/runc
    mode: 0755
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: runc_pkg
  until: runc_pkg is succeeded
  retries: 10
  notify: Start Containerd

- name: Download Containerd
  get_url:
    url: '{{ containerd_download_url }}'
    dest: '/usr/local/src/containerd-{{ CONTAINERD_VERSION }}.linux-amd64.tar.gz'
    mode: 0644
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: containerd_pkg
  until: containerd_pkg is succeeded
  retries: 10
  notify: Start Containerd

- name: Extract Containerd
  unarchive:
    src: '/usr/local/src/containerd-{{ CONTAINERD_VERSION }}.linux-amd64.tar.gz'
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
  notify: Start Containerd

- name: Download Crictl
  get_url:
    url: '{{ crictl_download_url }}'
    dest: '/usr/local/src/crictl-v{{ CRICTL_VERSION }}-linux-amd64.tar.gz'
    mode: 0644
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: crictl_pkg
  until: crictl_pkg is succeeded
  retries: 10
  notify: Start Containerd
  
- name: Extract Crictl
  unarchive:
    src: '/usr/local/src/crictl-v{{ CRICTL_VERSION }}-linux-amd64.tar.gz'
    dest: /usr/local/bin
    remote_src: yes

- name: Configuration Crictl
  template: 
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml

- name: Create Configuration directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /etc/containerd

- name: Configuration Containerd
  template: 
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify: Start Containerd

- name: Install systemd file
  template: 
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  notify: Start Containerd

- name: Install crictl completion
  copy: 
    src: crictl.sh
    dest: /etc/bash_completion.d/crictl
    owner: root
    group: root