- name: Create data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ kubernetes.addon.location }}/flannel'
  run_once: true
  when: "'kube-master' in group_names"

- name: Deployment flannel --- part.1
  template: 
    src: '{{ item.src }}'
    dest: '{{ kubernetes.addon.location }}/{{ item.dest }}'
  with_items:
    - { src: 'flannel/flannel.yaml.j2', dest: 'flannel/flannel.yaml' }
  run_once: true
  when: "'kube-master' in group_names"

- name: Deployment flannel --- part.2
  command: 'kubectl apply -f {{ kubernetes.addon.location }}/{{ item }}'
  with_items:
    - flannel/flannel.yaml
  run_once: true
  when: "'kube-master' in group_names"