- name: Update node roles for master
  shell: |
    {% if nodename is defined %}
      kubectl label node {{ nodename | lower }} {% if 'kube-master' in group_names %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/master=""{% endif %}
    {% else %}
      kubectl label node {{ hostvars[inventory_hostname].hostname  | lower }} {% if 'kube-master' in group_names %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/master=""{% endif %}
    {% endif %}